competition/competition/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
	

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("general.urls")),
    path("participants/",include("users.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

competition/general/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from general.views import home, logIn, overview , register, logOut, participants, competitions, participant, profile, enroll, leave
	

urlpatterns = [
    path('', overview),
    path('home/', home),
    path('login/', logIn),
    path('logout/', logOut),
    path('register/', register),
    path('participants/', participants),
    path('participant/<int:id>/', participant),
    path('profile/', profile),
    path('competitions/', competitions),
    path('competition/<int:id>/enroll/', enroll),
    path('competition/<int:id>/leave/', leave),
] 

competition/users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
	

urlpatterns = [
 #path('', admin.site.urls),
]

competition/general/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django_countries.fields import CountryField
# Create your models here.

# This to make email unqiue for users 
from django.contrib.auth.models import User
User._meta.get_field('email')._unique = True

class Skill(models.Model):
    name = models.CharField(max_length=265, unique=True)

    def __str__(self):
        return self.name

class Participant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True,null=True)
    title = models.CharField(max_length=265, default='Web Developer')
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")
    phone_number = models.CharField(validators = [phoneNumberRegex], max_length = 16, unique = True)
    photo = models.ImageField(upload_to='media/participants', null=True, blank=True)
    country = CountryField()
    skills = models.ManyToManyField(Skill, blank=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " - " + self.user.username

class Competition(models.Model):
    name = models.CharField(max_length=265, unique=True)
    description = models.CharField(max_length=1500, null=True, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    photo = models.ImageField(upload_to='media/competitions', null=True, blank=True)
    participants = models.ManyToManyField(Participant, blank=True)

    def __str__(self):
        return self.name

class Qualification(models.Model):
    description = models.CharField(max_length=265)
    competition = models.ForeignKey(Competition,on_delete=models.CASCADE, blank=True, null=True, related_name='qualifications')

    def __str__(self):
        return str(self.competition) + " - "  +  self.description[0:10] 

competition/general/forms.py
from django import forms
from .models import Participant, CountryField, Competition

class ParticipantForm_F(forms.ModelForm):
    class Meta:
        model = Participant
        fields = "__all__"
        widgets = {
            'user': forms.Select(attrs={'class':'form-control'}),
            'phone_number':  forms.TextInput(attrs={'class':'form-control'}),
            'country':  forms.Select(attrs={'class':'input'}),
            'skills':  forms.SelectMultiple(attrs={'class':'input picker'}),
            'photo':  forms.ClearableFileInput(attrs={'class':'input'}),
        }

competition/general/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from django.contrib.auth.models import User
from rest_framework.decorators import api_view
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import F
from .forms import ParticipantForm_F
from .serializers import ParticipantSerializer
from .models import Participant, Competition
from .functions import getPartiCountry, listCountryPartis, enrolledcompets, notenrolledcompets, fullcompets, adminUser, comptbyid
# Create your views here.

def overview(request):
    context = {'page_title':'Sager | Home'}
    try:
        user = request.user
        if user.is_authenticated == True:
            return redirect('/home')
        else:
            return render(request,'general/home.html', context)
    except:
        return render(request,'general/home.html', context)

@login_required(login_url='/login')
def home(request):
    if adminUser(request) == True:
        return redirect('/admin')
    context = { 'page_title':'Sager | Home'}
    return render(request,'general/home_reg.html', context)

@login_required(login_url='/login')
def competitions(request):
    if adminUser(request) == True:
        return redirect('/admin')
    enroll_competitions = enrolledcompets(request)
    noenroll_competitions = notenrolledcompets(request)
    context = {'notenrolled':noenroll_competitions, 'enrolled':enroll_competitions, 'page_title':'Sager | Competitions'}
    return render(request,'general/competitions.html', context)

@login_required(login_url='/login')
def participants(request):
    if adminUser(request) == True:
        return redirect('/admin')
    user = request.user
    user_country = getPartiCountry(request)
    country_participants = listCountryPartis(user_country).exclude(user=user)
    other_participants = Participant.objects.exclude(country=user_country)
    context = {'country':user_country,'country_participants':country_participants,'other_participants':other_participants ,'page_title':'Sager | Participants'}
    return render(request,'general/participants.html', context)

@login_required(login_url='/login')
def participant(request, id):
    if adminUser(request) == True:
        return redirect('/admin')
    user_country = getPartiCountry(request)
    participant = Participant.objects.get(id=id)
    country = participant.country.name
    context = {'country':country,'participant':participant,'page_title':'Sager | Participant Details'}
    return render(request,'general/participant.html', context)

@login_required(login_url='/login')
def profile(request):
    if adminUser(request) == True:
        return redirect('/admin')
    country = getPartiCountry(request).name
    user = request.user
    participant = Participant.objects.get(user=user)
    context = {'country':country,'participant':participant,'page_title':'Sager | My Profile'}
    return render(request,'general/profile.html', context)

def logIn(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request ,username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home')
        else:
            form = ParticipantForm_F()
            user = User.objects.filter(username=username)
            errors = 'There is no username with this input. Please try again'
            if len(user) > 0:
                errors = 'Password is wrong. Please try again'
            fields = {}
            for field in form:
                    fields[field.name] = field
            context = {'form':form, 'fields':fields, 'errors':errors, 'page_name':'Sign In | Register'}
            return render(request,'general/login.html', context)
    except:
        form = ParticipantForm_F()
        user = request.user
        fields = {}
        for field in form:
                fields[field.name] = field
        context = {'form':form, 'fields':fields, 'page_name':'Sign In | Register'}
        return render(request,'general/login.html', context)

@login_required(login_url='/login')
def logOut(request):
    logout(request)
    return redirect('/')

@api_view(['POST'])
def register(request):
    data = request.data
    # print(data)
    part_data = {}
    user_data = {}
    user_data['username'] = data['user']
    user_data['password'] = data['pass']
    user_data['email'] = data['email']
    user_data['first_name'] = data['first_name']
    user_data['last_name'] = data['last_name']
    part_data['phone_number'] = data['phone_number']
    part_data['country'] = data['country']
    part_data['photo'] = data['photo']
    part_data['title'] = data['title']
    part_data['skills'] = request.POST['skills'].split(',')
    # print(part_data)
    serializer = ParticipantSerializer(data= part_data)
    if serializer.is_valid():
        # create user
        try:
            user = User.objects.create_user(username=user_data['username'],email=user_data['email'],password=user_data['password'],first_name= user_data['first_name'],last_name=user_data['last_name'])
            serializer.save()
            # print(serializer.data)
            parti = Participant.objects.get(id=serializer.data['id'])
            parti.user = user
            parti.save()
            # This to login the user
            user = authenticate(request ,username=user_data['username'], password=user_data['password'])
            if user is not None:
                login(request, user)
                return Response({'200':'Login the user'})
            else:
                Response({'errors':'The user has not been created successfully'})
        except Exception as e:
            error = []
            if 'email' in e.__str__():
                error.append('The email is already exist')
            elif 'username' in e.__str__():
                error.append('The username is already exist')
            return Response({'errors':error})
    else:
        return Response({'errors':serializer.errors})


    querys = list(User.objects.all().values())
    queryset = User.objects.all().values()
    # print(querys)
    # print(querys.values())
    serializer = UserSerializer(data=queryset)
    print(serializer)
    # return Response(serializer.data)
    return Response(serializer.initial_data)

@login_required(login_url='/login')
@api_view(['PUT'])
def enroll(request, id):
    user = request.user
    participant = Participant.objects.get(user=user)
    competition = Competition.objects.get(id=id)
    try:
        competition.participants.add(participant)
        return Response({'message':'Congrats! You have enrolled'})
    except Exception as e:
        error = []
        error.append(e.__str__())
        print('There is an error')
        return Response({'errors':error})

@login_required(login_url='/login')
@api_view(['PUT'])
def leave(request, id):
    user = request.user
    participant = Participant.objects.get(user=user)
    competition = Competition.objects.get(id=id)
    try:
        competition.participants.remove(participant)
        return Response({'message':'Done! You have left'})
    except Exception as e:
        error = []
        error.append(e.__str__())
        return Response({'errors':error})

competition/templates/general/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Change Title
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'picker/picker.min.css' %}">
</head>
<body>
    {% include 'css/nav-css.html' %}
    {% block style %}
    {% endblock %}
    <div class='dashboard'>
        <div class="dashboard-nav">
            <header><a href="#" class="menu-toggle"><i class="fas fa-bars"></i></a><a href="/"
                                                                                       class="brand-logo"><i class="fas fa-cubes"></i> <span>Competitions</span></a></header>
            <nav class="dashboard-nav-list">
                <a href="/" class="dashboard-nav-item"><i class="fas fa-home"></i>
                Home </a>
                {% if user.is_authenticated %}
                <a href="/profile" class="dashboard-nav-item"><i class="fas fa-user-circle"></i>
                My Profile </a>
                <a href="/participants" class="dashboard-nav-item"><i class="fas fa-users"></i> Participants </a>
                <a href="/competitions" class="dashboard-nav-item"><i class="fab fa-free-code-camp"></i> Competitions </a>
                    {% endif %}
                <!-- <div class='dashboard-nav-dropdown'><a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle"><i
                        class="fas fa-photo-video"></i> Media </a>
                    <div class='dashboard-nav-dropdown-menu'><a href="#"
                                                                class="dashboard-nav-dropdown-item">All</a><a
                            href="#" class="dashboard-nav-dropdown-item">Recent</a><a
                            href="#" class="dashboard-nav-dropdown-item">Images</a><a
                            href="#" class="dashboard-nav-dropdown-item">Video</a></div>
                </div>
                <div class='dashboard-nav-dropdown'><a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle"><i
                        class="fas fa-users"></i> Users </a>
                    <div class='dashboard-nav-dropdown-menu'><a href="#"
                                                                class="dashboard-nav-dropdown-item">All</a><a
                            href="#" class="dashboard-nav-dropdown-item">Subscribed</a><a
                            href="#"
                            class="dashboard-nav-dropdown-item">Non-subscribed</a><a
                            href="#" class="dashboard-nav-dropdown-item">Banned</a><a
                            href="#" class="dashboard-nav-dropdown-item">New</a></div>
                </div>
                <div class='dashboard-nav-dropdown'><a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle"><i
                        class="fas fa-money-check-alt"></i> Payments </a>
                    <div class='dashboard-nav-dropdown-menu'><a href="#"
                                                                class="dashboard-nav-dropdown-item">All</a><a
                            href="#" class="dashboard-nav-dropdown-item">Recent</a><a
                            href="#" class="dashboard-nav-dropdown-item"> Projections</a>
                    </div>
                </div>
                <a href="#" class="dashboard-nav-item"><i class="fas fa-cogs"></i> Settings </a>
                <a href="#" class="dashboard-nav-item"><i class="fas fa-user"></i> Profile </a> -->
              <div class="nav-item-divider"></div>
                {% if user.is_authenticated %}
              <a href="/logout" class="dashboard-nav-item"><i class="fas fa-sign-out-alt"></i> Logout </a>
              {% else %}
              <a href="/login" class="dashboard-nav-item"><i class="fas fa-sign-out-alt"></i> Login | Register </a>
              {% endif %}
            </nav>
        </div>
        <div class='dashboard-app'>
            <header class='dashboard-toolbar justify-content-between'>
                <a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a>
                {% if user.is_authenticated %}
                <h4>Hello, <a href="/profile" class="text-decoration-none" style="color: white;">{{user.first_name}}</a></h4>
                {% endif %}
            </header>
            <div class='dashboard-content'>
                <div class='container'>
                    
    
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'jquery/jquery-3.6.0.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'picker/picker.min.js'%}" type="text/javascript"></script>
    {% include 'scripts/nav-js.html' %}
    {% block scripts %}

    {% endblock %}
</body>
</html>

competition/templates/general/competitions.html
{% extends "general/base.html" %}
{% block title %}
{{page_title}}
{% endblock %}

{% block style %}
{% include 'css/comp-css.html' %}
{% endblock %}

{% block content %}

<div class="unenrolled-compts">
{% for compt in notenrolled %}
<div class="p-3"  compt_id="{{compt.id}}">
  <article class="recipe bg-white">
   <div class="pizza-box">
     <img src="/media/{{compt.photo}}" width="200" height="300" alt="">
   </div>
   <div class="recipe-content ">
     <!-- <p class="recipe-tags">
       <span class="recipe-tag">Gluten Free</span>
       <span class="recipe-tag">Main dish</span>
     </p> -->

     <h1 class="recipe-title"><a href="#">{{compt.name}}</a></h1>
    <!-- 
     <p class="recipe-metadata">
       <span class="recipe-rating">★★★★<span>☆</span></span>
       <span class="recipe-votes">(12 votes)</span>
     </p> -->
    <br>
     <p class="recipe-desc"> 
      <span style="color: #e6d200; font-weight: bold;">Description: </span> {{compt.description}}
      </p>
     <p class="recipe-desc">
       <span style="color: #e6d200; font-weight: bold;">Qualifications:</span>
       <ol>
       {% for item in compt.quali %}
        <li>{{item}}</li> 
       {% endfor %}
      </ol>
      </p>

     <button class="recipe-save bg-transparent notenrolled" compt_id="{{compt.id}}" type="button">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-save2-fill" viewBox="0 0 16 16">
        <path d="M8.5 1.5A1.5 1.5 0 0 1 10 0h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h6c-.314.418-.5.937-.5 1.5v6h-2a.5.5 0 0 0-.354.854l2.5 2.5a.5.5 0 0 0 .708 0l2.5-2.5A.5.5 0 0 0 10.5 7.5h-2v-6z"/>
      </svg>
       Enroll
     </button>

   </div>
 </article>
</div>
{% endfor %}
</div>
<div class="enrolled-compts">
{% for compt in enrolled %}
<div class="p-3">
  <article class="recipe bg-white">
   <div class="pizza-box">
     <img src="/media/{{compt.photo}}" width="200" height="300" alt="">
   </div>
   <div class="recipe-content ">
     <!-- <p class="recipe-tags">
       <span class="recipe-tag">Gluten Free</span>
       <span class="recipe-tag">Main dish</span>
     </p> -->

     <h1 class="recipe-title"><a href="#">{{compt.name}}</a></h1>
    <!-- 
     <p class="recipe-metadata">
       <span class="recipe-rating">★★★★<span>☆</span></span>
       <span class="recipe-votes">(12 votes)</span>
     </p> -->
    <br>
     <p class="recipe-desc"> 
      <span style="color: #e6d200; font-weight: bold;">Description: </span> {{compt.description}}
      </p>
     <p class="recipe-desc">
       <span style="color: #e6d200; font-weight: bold;">Qualifications:</span>
       <ol>
       {% for item in compt.quali %}
        <li>{{item}}</li> 
       {% endfor %}
      </ol>
      </p>

     <button class="recipe-save bg-info enrolled" compt_id="{{compt.id}}" type="button">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg>
       Enrolled
     </button>

   </div>
 </article>
</div>
{% endfor %}
</div>

<!-- Modal -->
<div class="modal fade" id="leave-modal" tabindex="-1" role="dialog" aria-labelledby="leave-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="leave-modal-label">Confirmation</h5>
        <button type="button" class="btn-close" data-dismiss="modal" id="leave-hide" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to leave the competition?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="leave-decline">No</button>
        <button type="button" class="btn btn-danger" id="leave-confirm">Yes</button>
      </div>
    </div>
  </div>
</div>

<div class="alert alert-success fade show" id="success-message" role="alert">
  <span id="success-message-text">Great! You have enrolled</span>
  <button type="button" class="btn-close" id="close-success" aria-label="Close"></button>
</div>

<div class="alert alert-danger fade show" id="error-message" role="alert">
 <span id="error-message-text">Sorry! There is a problem, please try again</span>
  <button type="button" class="btn-close" id="close-error" aria-label="Close"></button>
</div>

{% endblock %}

{% block scripts %}
{% include 'scripts/comp-js.html' %}
{% endblock %}

competition/templates/general/home.html
{% extends "general/base.html" %}
{% block title %}
Home | Sager
{% endblock %}

{% block content %}

<div class="card">
  <h5 class="card-header">Hello, are you new here?</h5>
  <div class="card-body">
    <p>
      This website is to enroll competitions and to see the pariticipants ...
    </p>
  </div>
  <div class="card-footer"> 
    <div class="row justify-content-center text-center">
    <div class="col-12">
      <a href="/login"><button class="btn btn-dark"> Login | Register</button></a>
    </div>
  </div>
</div>

 
  

  </div>
{% endblock %}

{% block scripts %}
<script>
$("#hello").css('color','green')
</script>
{% endblock %}

competition/templates/general/home_reg.html
{% extends "general/base.html" %}
{% block title %}
{{page_title}}
{% endblock %}

{% block style %}
{% include 'css/home_reg-css.html' %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
    <!-- these radio buttons hold state of which card is in front and which toggle button is visible -->
    <input type="radio" name="sushi-lunch" id="happy-radio">
    <input type="radio" name="sushi-lunch" id="lovers-radio" checked>
  
    <div class="selector">
      <label for="happy-radio" class="happy-card">
        <h1>Competitions</h1>
        <ul>
          <li>You will see competitions and enroll</li>
        </ul>
        <a href="/competitions"><p>See Competitions</p></a>
      </label>
  
      <label for="lovers-radio" class="lovers-card">
        <h1>Participants</h1>
        <ul>
          <li>You will see participants from your country</li>
        </ul>
        <a href="/participants"><p>See Participants</p></a>
      </label>
      
      <label for="happy-radio" class="happy-pick">Switch to Competitions</label>
      <label for="lovers-radio" class="lovers-pick">Switch to Participants</label>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>

</script>
{% endblock %}

competition/templates/general/login.html
{% extends "general/base.html" %}
{% block title %}
Login | Register
{% endblock %}
{% block style %}
    {% include 'css/login-css.html' %}
{% endblock %}

{% block content %}

<div id="error-container" class="justify-content-center"
	{% if errors %}
	style="display: block;"
	{% else %}
 style="display: none;"
	{% endif %}
 >
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>Sorry!</strong> <span id="error-message">{{errors}}</span>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	  </div>
</div>

<div class="login-container">
<div class="card text-white bg-dark mb-3" style="width: 90%;">
	<div class="card-header">
		<ul class="nav nav-pills mb-3 mt-3 justify-content-center" id="pills-tab" role="tablist">
			<li class="nav-item" role="presentation">
			  <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-signin" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Sign In</button>
			</li>
			<li class="nav-item" role="presentation">
			  <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-register" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Register</button>
			</li>
		  </ul>
	  </div>

  <div class="tab-content text-center" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-signin" role="tabpanel" aria-labelledby="pills-home-tab">

			<div class="card-body">
				<div class="login-form">
					<form action="/login/" method="POST">
						{% csrf_token %}
					<div class="sign-in-htm">
						<div class="row justify-content-center">
							<div class="group col-lg-4 col-12">
								<label for="username" class="label">Username</label>
								<input id="username" name="username" type="text" class="input" required>
							</div>
							<div class="group col-lg-4 col-12">
								<label for="password" class="label">Password</label>
								<input id="password" name="password" type="password" class="input" data-type="password" required>
							</div>
						</div>
						<div class="row justify-content-center">
						<div class="group col-lg-4 col-12">
							<input type="submit" class="button" value="Sign In">
						</div>
						</div>
						<div class="hr"></div>
						<!-- <div class="foot-lnk">
							<a href="#forgot">Forgot Password?</a>
						</div> -->
						<div class="foot-lnk go-register">
							<p>Are you a new member? <span><a href="#">Register Now</a></span></p>
						</div>
					</div>
					</form>
				</div>
			</div>
	</div>

    <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="pills-profile-tab">

			<div class="card-body">
				<div class="login-form">
					<form action="/" data-enctype="multipart/form-data" method="POST" id="register-form">
					<div class="sign-up-htm">
						
						<div class="row justify-content-center">
							<div class="group col-lg-4 col-12">
								<label for="first_name" class="label">First Name</label>
								<input id="first_name" type="text" class="input" name="first_name"required>
							</div>
							<div class="group col-lg-4 col-12">
								<label for="last_name" class="label">Last Name</label>
								<input id="last_name" type="text" class="input" name="last_name" required>
							</div>
							<div class="group col-lg-4 col-12">
								<label for="user" class="label">Username</label>
								<input id="user" type="text" class="input" name="user" required>
							</div>
							<div class="group col-lg-4 col-12">
								<label for="title" class="label">Title</label>
								<input id="title" type="text" class="input" name="title" title="Example: Web developer, Software Engineer" required>
							</div>
							<div class="group col-lg-4 col-12">
								<label for="photo" class="label">Photo</label>
								<!-- <input id="photo" type="file" class="input" name="photo" required> -->
								{{fields.photo}}
							</div>
							<div class="group col-lg-4 col-12">
								<label for="id_country" class="label">Country</label>
								{{fields.country}}
							</div>
							<div class="group col-lg-4 col-12">
								<label for="id_skills" class="label">Skills</label>
								{{fields.skills}}
							</div>
							<div class="group col-lg-4 col-12">
								<label for="phone_number" class="label">Phone Number</label>
								<input id="phone_number" name="phone_number" type="tel" class="input" pattern="^\+?1?\d{8,15}$" title="Please enter Number like this: +96279000000 which starts with country code" required>
							</div>
							<div class="group col-lg-4 col-12">
								<label for="email" class="label">Email Address</label>
								<input id="email" name="email" type="email" class="input" title="Please enter valid email. example@cc.com">
							</div>
							<div class="group col-lg-4 col-12">
								<label for="pass" class="label">Password</label>
								<input id="pass" name="pass" type="password" class="input" data-type="password" required>
							</div>
						</div>

						<div class="row justify-content-center">
							<div class="group col-lg-4 col-12">
								<input type="submit" class="button" value="Sign Up">
							</div>
						</div>
						<div class="hr"></div>
						  
						<div class="foot-lnk go-signin">
							<a href="#" >
							<label for="tab-1" style="text-decoration: underline;
							cursor: pointer;">Already Member?</a>
							</a>
						</div>
					</div>
					</form>
				</div>
			</div>

	</div>

  </div>
</div>
</div>
{% endblock %}

{% block scripts %}
{% include 'scripts/login-js.html' %}
{% endblock %}

competition/templates/general/participants.html
{% extends "general/base.html" %}
{% block title %}
{{page_title}}
{% endblock %}

{% block style %}
{% include 'css/parts-css.html' %}
{% endblock %}

{% block content %}

{% if country_participants %}
<div class="card mb-5">
  <h5 class="card-header">
    Participants live in {{country.name}}
  </h5>
  <div class="card-body">
    <div class="container">
      <div class="row">
          {% for part in country_participants %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <a href="/participant/{{part.id}}/" class="text-decoration-none">
          <div class="our-team">
            <div class="picture">
              <img class="img-fluid" src="/media/{{part.photo}}">
            </div>
            <div class="team-content">
              <h3 class="name">{{part.user.first_name}}</h3>
              <h4 class="title">{{part.title}}</h4>
            </div>
          </div>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>



  {% endif %}

  <div class="card">
    <h5 class="card-header">
      All other pariticipants
    </h5>
    <div class="card-body">
      <div class="container">
        <div class="row">
            {% for part in other_participants %}
          <div class="col-12 col-sm-6 col-md-4 col-lg-3">
              <a href="/participant/{{part.id}}/" class="text-decoration-none">
            <div class="our-team">
              <div class="picture">
                <img class="img-fluid" src="/media/{{part.photo}}">
              </div>
              <div class="team-content">
                <h3 class="name">{{part.user.first_name}}</h3>
                <h4 class="title">{{part.title}}</h4>
              </div>
            </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

    
   

{% endblock %}

{% block scripts %}
<script>
$("#hello").css('color','green')
</script>
{% endblock %}